name: Tests with docker
on:
  push:
    paths-ignore:
    - docs/requirements.txt
    - examples/**

jobs:
  Linux:
    runs-on: ubuntu-20.04
    container:
      image: docker://jcolley/grandlib_ci:0.1 
      
    steps:    
    - uses: actions/checkout@v2
    - name: Initialise the environment      
      run: |
        source env/setup.sh
        quality/ci/coverage_if_necessary.bash
      shell: bash

    - name: Check SonarQube update
      env:
        USER_GIT: ${{github.actor}}
        SONAR_L: ${{secrets.SONAR_TOKEN}}
      run: |
        pwd
        ls -la
        . env/test.sh $PWD
        quality/ci/manage_sonar_update.py "$SONAR_L"
        . quality/ci/apply_sonar_update.bash

    - name: Dynamics analysis and coverage
      run: |
        . env/setup.sh        
        quality/ci/coverage_if_necessary.bash
        check_score_coverage.py
        
    - name: Static analysis with pylint
      run: |
        . env/setup.sh                
        grand_quality_analysis.bash
        
    - name: Static type check
      run: |
        . env/setup.sh
        grand_quality_type.bash 
